# https://hub.docker.com/_/mysql
version: "3.6"

services:
  dbm:
    image: mysql:5.7
    #container_name: mysqldbm
    # build: .
    restart: always
    env_file:
      - .env
    # environment:
    # MYSQL_DATABASE: test
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - mysqldata:/var/lib/mysql/  # folder for mysql's internal data files.
      # - ../datasys/mysql${PWD}:/var/lib/mysql/  # folder for mysql's internal data files.
      # - .:/root # folder for scripts, etc.
      # - ../data/mysqlhome${PWD}/:/home # folder for exported data, etc.
    # networks:
    #   - sister2
    # https://medium.freecodecamp.org/how-to-setup-log-rotation-for-a-docker-container-a508093912b2
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "3"

  adminer:
    # 10.4.1.231:6117/  use db or 10.4.1.228:3308 for server while logging in.
    image: adminer:4.7
    restart: always
    env_file:
      - .env    
    ports:
      - 6117:8080
    # networks:
    #   - sister2

volumes:
  mysqldata:

    
# https://docs.docker.com/compose/compose-file/#external-1
# networks:
#   sister2:
#     name:
#       sister2
#external:true
#I tried lining up external under name and got:
# albe@pmdsdata4:/srv/dkr/392dkr/backend392$ make myrup
# docker-compose  up --build  --force-recreate
# ERROR: yaml.scanner.ScannerError: while scanning a simple key
# in "./docker-compose.yml", line 33, column 5
# could not find expected ':'
# in "./docker-compose.yml", line 35, column 3
# make: *** [myrup] Error 1
# net2:
# external:
# name: netw2
# albe@pmdsdata4:/srv/dkr/392dkr/backend392$ make myrup
# docker-compose  up --build  --force-recreate
# WARNING: Some networks were defined but are not used by any service: net2
# ERROR: Service "dbm" uses an undefined network "netw2"
# make: *** [myrup] Error 1
# network:
# external: true
# name: mynet3
# albe@pmdsdata4:/srv/dkr/392dkr/backend392$ make myrup
# docker-compose  up --build  --force-recreate
# WARNING: Some networks were defined but are not used by any service: network3
# ERROR: Service "dbm" uses an undefined network "mynet3"
# make: *** [myrup] Error 1
