version: '3.6'

services:
  nodejs:
    working_dir: /app
    build:
      context: ./nodeapp
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - MONGO_HOSTNAME=dbxx 
    expose: 
      - 8080
    ports:
      - "14807:8080"
    volumes:
      - ./nodeapp:/app
      # - node_modules:/home/sysdata/node_modules
    # command: ./wait-for.sh db:27017 -- /home/sysdata/node_modules/.bin/nodemon app.js
    # command: node server.js



  # mongodb:
  #   image: mongo:4.2-bionic
  #   container_name: db
  #   env_file: .env
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
  #     - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
  #   volumes:  
  #     - dbdata:/data/db   

# volumes:
  # dbdata:
  # node_modules:      

