version: "3.6"

services:
  
  nodejs:
    working_dir: /app
    build:
      context: ./nodeapp
      dockerfile: Dockerfile
    # env_file: .env
    environment:
      - MONGO_HOSTNAME=dbxx 
    expose: 
      - 8080
      - 3000
    ports:
      - "14807:3000"
    volumes:
      - ./nodeapp:/app
      # - node_modules:/home/sysdata/node_modules
    # command: ./wait-for.sh db:27017 -- /home/sysdata/node_modules/.bin/nodemon app.js
    command: node index.js

  adminerd:
    # 10.4.1.231:6117/
    # image: adminer:4.7
    # image: dockette/adminer:full
    # image: dgleba/adminer-sqlite:one
    build: ./adminer-sqlite
    # restart: always
    ports:
      - 14226:80
      # 8080 for regular adminer, 80 for dockette
    volumes:
      - ./nodeapp/data/apptest.db:/db.sq3
      - ./adminer-sqlite:/var/www/html
    environment:
      - ADMINER_DEFAULT_SERVER=srv
      - DB_PATH=/db.sq3
      - DB_USER=user
      - DB_PASS=apass
      # - ADMINER_PLUGINS='tables-filter'




# for redis, see django-select2 example.. https://github.com/codingjoe/django-select2/tree/master/example
      # and  https://github.com/wildfish/wildfish-django-starter/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/dev-docker-compose.yml.default


# networks:
#   548-flask_default:
#     name: 548-flask_default



